### ISSUE TITLE
Where do i place the Navigation CSS?

### ISSUE THREAD

**Issue by datatalking** [shacker/django-todo#106]
I'm doing a complete reinstall and now I'm getting a crash when I try to login (which it should right I don't have the todo setup)
My front end skills are not sufficent to understand where the two css lines go.

stack trace error 
`
$ python manage.py migrate todo
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/owner/anaconda3/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/owner/anaconda3/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/Users/owner/anaconda3/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/owner/anaconda3/lib/python3.7/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/Users/owner/anaconda3/lib/python3.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/Users/owner/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django_extensions'
`

I don't know where to put these.
In README.md it references two sets of two lines of CSS code that look like

Blockset
`{% block extrahead %}{% endblock extrahead %}`
`{% block extra_js %}{% endblock extra_js %}`

and these

ahrefset
`  <a href="{% url 'todo:lists' %}">Todo Lists</a>`
` <a href="{% url 'todo:mine' %}">My Tasks</a>`

It says to "Add links to your site's navigation system:"

1. What file name and line to I "add" these two lines of css ?

**Comment by shacker** [comment]
The error you're getting is because you haven't installed the project dependencies - you've specified django_extensions but haven't installed it (`pip install django-extensions` from within the env), or you haven't activated your environment.

As noted in docs, the CSS lines go in your project's base.html alongside other CSS and JS links.

**Comment by shacker** [comment]
Closing this - this is a general support question best suited for the django-users mailing list, no relation to this project.
