### ISSUE TITLE
django mezzanine install of your django-todo app

### ISSUE THREAD

**Issue by datatalking** [shacker/django-todo#38]
I currently have a django/mezzanine app that runs and when I install this app i get a couple errors.

mkl-random 1.0.1 requires cython, which is not installed.
mkl-fft 1.0.0 requires cython, which is not installed.
Installing collected packages: unidecode, django-todo
Successfully installed django-todo-2.0.3 unidecode-1.0.22

It says error but then says successful django install, so I figure things might work, I put todo in my apps list and go to rerun the server and get the following error.

Unhandled exception in thread started by <function wrapper at 0x10d7997d0>
Traceback (most recent call last):
  File "/Users/owner/Code/mezzanine_env/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Users/owner/Code/mezzanine_env/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/Users/owner/Code/mezzanine_env/lib/python2.7/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/Users/owner/Code/mezzanine_env/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Users/owner/Code/mezzanine_env/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/owner/Code/mezzanine_env/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/owner/Code/mezzanine_env/lib/python2.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named todo

If mezzanine_env is my virtual env and its subfolder mezzanine_app is where my files are, is there a specific place where i should install this app?

In your notes you also mention some css links, where would those go as I am not seeing an existing css page in my django app.

Thanks in advance.

**Comment by datatalking** [comment]
I should append this to note that I am trying to load this app in a pythonanywhere 2.7 container.
